# Generated by Django 4.1.6 on 2023-02-03 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('preco', models.DecimalField(decimal_places=2, max_digits=6)),
                ('qtd', models.IntegerField()),
                ('validade', models.DateField()),
                ('disponibilidade', models.BooleanField()),
                ('descricao', models.TextField(default='')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.categoria')),
            ],
        ),
    ]
