# Generated by Django 4.1.7 on 2023-02-24 19:07

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=14)),
                ('celular', models.CharField(max_length=10)),
                ('data_nascimento', models.DateField()),
                ('data_cadastro', models.DateField(auto_now=True)),
                ('tipo_cliente', models.CharField(choices=[('F', 'Free'), ('P', 'Premium'), ('M', 'Master')], default='F', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_pedido', models.DateField(auto_now=True)),
                ('status_pedido', models.CharField(choices=[('E', 'Entregue'), ('X', 'Cancelado'), ('C', 'à Caminho'), ('C', 'Preparação'), ('C', 'Aguardando')], default='A', max_length=1)),
                ('metodo_pagamento', models.CharField(choices=[('PI', 'PIX'), ('CC', 'CARTÃO DE CRÉDITO'), ('CD', 'CARTÃO DE DÉBITO'), ('BO', 'BOLETO')], default='CD', max_length=2)),
                ('total_pagamento', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1, message='O preço deve ser igual ou maior que 1 real'), django.core.validators.MaxValueValidator(1000)])),
                ('status_pagamento', models.CharField(choices=[('N', 'NEGADO'), ('A', 'EM ANALISE'), ('C', 'CONFIRMADO')], default='A', max_length=1)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendas.clientes')),
            ],
            options={
                'verbose_name_plural': 'Pedidos',
            },
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categoria'},
        ),
        migrations.AlterModelOptions(
            name='produtos',
            options={'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nome',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='preco',
            field=models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1, message='O preço deve ser igual ou maior que 1 real'), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='qtd',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0, message='A quantidade não deve ser negativa')]),
        ),
        migrations.CreateModel(
            name='PedidosItens',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtd', models.IntegerField(validators=[django.core.validators.MinValueValidator(1, message='A quantidade deve ser igual ou maior que 1')])),
                ('preco_atual', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(1, message='O preço deve ser igual ou maior que 1 real')])),
                ('preco_total', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1, message='O preço deve ser igual ou maior que 1 real')])),
                ('fk_pedidos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.pedidos')),
                ('fk_produtos', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vendas.produtos')),
            ],
            options={
                'verbose_name_plural': 'Pedidos Itens',
            },
        ),
        migrations.CreateModel(
            name='Fornecedores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa_nome', models.CharField(max_length=255)),
                ('cnpj', models.CharField(max_length=14, unique=True)),
                ('contato_email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=10)),
                ('data_cadastro', models.DateField(auto_now=True)),
                ('categoria_fornecida', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vendas.categoria')),
            ],
            options={
                'verbose_name_plural': 'Fonecedores',
            },
        ),
    ]
