# Generated by Django 4.1.7 on 2023-05-05 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('cpf', models.CharField(max_length=20)),
                ('foto_logo', models.CharField(default='teste', max_length=100)),
                ('data_nascimento', models.DateField()),
                ('celular', models.CharField(max_length=20)),
                ('tipo_cliente', models.CharField(choices=[('F', 'Free'), ('P', 'Premium'), ('M', 'Master')], default='F', max_length=1)),
            ],
            options={
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Contas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_abertura', models.DateField(auto_now=True)),
                ('agencia', models.CharField(max_length=10)),
                ('numero', models.CharField(max_length=25, unique=True)),
                ('ativa', models.BooleanField()),
                ('senha', models.CharField(max_length=6)),
                ('limite', models.IntegerField(default=1000)),
                ('saldo', models.IntegerField()),
                ('clienteConta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.clientes')),
            ],
            options={
                'verbose_name_plural': 'Contas',
            },
        ),
        migrations.CreateModel(
            name='Transferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_enviado', models.IntegerField(verbose_name=0)),
                ('tipo', models.CharField(choices=[('D', 'Deposito'), ('T', 'Transferencia'), ('P', 'Pix')], default='T', max_length=1)),
                ('data_hora', models.DateField(auto_now=True)),
                ('contaTransferencia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.contas')),
            ],
            options={
                'verbose_name_plural': 'Transferencias',
            },
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=100)),
                ('bairro', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=50)),
                ('clienteEndereco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.clientes')),
            ],
        ),
    ]
