# Generated by Django 4.2.1 on 2023-06-10 22:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cartao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=16)),
                ('validade', models.DateField()),
                ('cvv', models.CharField(max_length=3)),
                ('conta_cartao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.contas')),
            ],
            options={
                'verbose_name_plural': 'Cartões',
            },
        ),
    ]
