# Generated by Django 4.1.7 on 2023-05-05 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contas',
            name='ativa',
            field=models.BooleanField(default=True),
        ),
    ]
