# Generated by Django 4.2 on 2023-05-10 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_alter_contas_ativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contas',
            name='ativa',
            field=models.CharField(choices=[('A', 'Ativa'), ('D', 'Desativada')], default='A', max_length=1),
        ),
    ]
