# Generated by Django 4.2 on 2023-05-10 17:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_contas_ativa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='celular',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='contas',
            name='agencia',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='contas',
            name='limite',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(1, message='O limite deve ser maior ou igual que 1 real'), django.core.validators.MaxValueValidator(1000)]),
        ),
        migrations.AlterField(
            model_name='contas',
            name='numero',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='contas',
            name='senha',
            field=models.CharField(max_length=4),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='bairro',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='cidade',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='rua',
            field=models.CharField(max_length=40),
        ),
    ]
