# Generated by Django 4.2 on 2023-05-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_alter_clientes_celular_alter_clientes_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contas',
            name='limite',
            field=models.IntegerField(),
        ),
    ]
