# Generated by Django 4.2 on 2023-05-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_alter_contas_limite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contas',
            old_name='clienteConta',
            new_name='cliente_conta',
        ),
        migrations.RenameField(
            model_name='endereco',
            old_name='clienteEndereco',
            new_name='cliente_endereco',
        ),
        migrations.RenameField(
            model_name='transferencias',
            old_name='contaTransferencia',
            new_name='conta_transferencia',
        ),
        migrations.AlterField(
            model_name='transferencias',
            name='valor_enviado',
            field=models.IntegerField(),
        ),
    ]
