# Generated by Django 4.2 on 2023-05-18 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0007_alter_clientes_cpf'),
    ]

    operations = [
        migrations.AddField(
            model_name='transferencias',
            name='conta_remetente',
            field=models.CharField(default=True, max_length=15),
        ),
    ]
