# Generated by Django 4.2 on 2023-05-19 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_transferencias_conta_remetente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transferencias',
            name='conta_transferencia',
            field=models.CharField(default=True, max_length=15),
        ),
    ]
