# Generated by Django 4.2 on 2023-05-23 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0010_clientes_date_joined_clientes_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contas',
            name='cliente_conta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, unique=True),
        ),
    ]
